# -*- coding: utf-8 -*-
"""Copy of Q&A activity student file.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k2KHlZYQq1oq5Z2EPp4azwyx1ETO1MbL

## 1. Complete the following code to find the area of an equilateral triangle. Output should be as displayed
"""

import math
side = float(input("Enter the side of the equilateral triangle: "))
area = ((math.sqrt(3))/4)*pow(side,2)
print(round(area,3))

"""## 2. Write a program to count the number of each characters in a string"""

a = []
string = input('enter string\n')
for i in string:
    if i in a:
        continue
    else:
        a.append(i)
        print(i,'=',string.count(i))

"""## Write a program to find the area and perimeter of a rectangle using functions"""

def area(l,b):
  return l*b
def perimeter(l,b):
  return 2*(l+b)
length = int(input('Enter length'))  
breadth = int(input('Enter breadth'))
print(area(length,breadth))
print(perimeter(length,breadth))

"""## 4. Write a program to print the fibonacci series till a specified number"""

n = int(input('Enter limit'))
n1 = 0
n2 = 1
n3 =0
print(n1)
print(n2)
while(n3 < n):
  n3 = n2+n1
  n1 = n2
  n2=n3
  print(n3)

"""## 5. Complete the following code to find the minimum of 3 number using cinditional statements. Output should be as displayed"""

a,b,c = [int(x) for x in input("Enter three numbers followed by  : ").split()]

print("First number :",a)
print("Second number :",b)
print("Third number :",c)

if(a==b and a==c):
    print("Entered numbers are equal!!!")
elif(a<b and a<c):
    print(a," is smallest")
elif(b<a and b<c):
    print(b," is smallest")
else:
    print(c," is smallest")

a,b,c = input("Enter three numbers followed by space : ").split()

print("First number :",a)
print("Second number :",b)
print("Third number :",c)

    print("Entered numbers are equal!!!")

    print(a," is smallest")

    print(b," is smallest")

    print(c," is smallest")

"""## 6. Write a program to print star pyramind. The number of rows should be taken as input from the user"""

n = int(input('enter row count'))
for i in range(0,n):
  for j in range(0,i+1):
    print('*',end="")
  print('\r')

"""## 7. Complete the following code to convert hour into seconds. Output should be as displayed"""

def to_seconds(t):
    t = t*3600
    return t
time_in_hours = int(input('Enter time in Hours :'))
print(time_in_hours ," Hour is equal to" ,to_seconds(time_in_hours) ," Seconds")

"""## 8. Write a program to print multiplication table as below"""

n = int(input('Enter a number to find the multiplication table: '))
for i in range(1,11):
  print(i,' x ',n,' = ',i*n)

"""## 9. Write a program to take your 5 favorite food as list and print each as 'I like Biriyani'"""

food = input('Enter your favorite food list followed by space : ').split()
for i in food:
  print('I like ',i)

"""## 10. Find error(s) in the following code(if any) and rewrite code.


"""

x= int(input("Enter value of x:"))
for y in range(0,10):
     if x==y:
          print("They are equal")
     else:
         print( "They are unequal")